//! `oxide generate` — controllers, routes, middleware stubs.

use anyhow::{Context, Result, bail};
use std::fs;
use std::path::PathBuf;

const ROUTE_MARKER: &str = "// oxide-framework-cli:routes";

pub fn controller(name: &str, prefix: &str, style: &str, force: bool) -> Result<()> {
    let style = style.trim().to_ascii_lowercase();
    if style != "macro" && style != "functional" {
        bail!("--style must be `macro` or `functional`");
    }
    let struct_name = controller_struct_name(name);
    let file_base = struct_name_to_snake_file(&struct_name);

    match style.as_str() {
        "macro" => {
            let path = PathBuf::from("src/controllers").join(format!("{file_base}.rs"));
            if path.exists() && !force {
                bail!(
                    "`{}` already exists — pass `--force` to overwrite",
                    path.display()
                );
            }
            write_macro_controller(&path, &struct_name, prefix, force)?;
            upsert_controllers_mod(&struct_name, &file_base)?;
            println!("Generated `{}`", path.display());
            println!("Register in `main.rs`: `.controller::<{struct_name}>()`");
        }
        "functional" => {
            fs::create_dir_all("src/routes").ok();
            let path = PathBuf::from("src/routes").join(format!("{file_base}.rs"));
            if path.exists() && !force {
                bail!(
                    "`{}` already exists — pass `--force` to overwrite",
                    path.display()
                );
            }
            write_functional_routes(&path, name, prefix, force)?;
            upsert_routes_mod(&file_base)?;
            let module = snake_module_name(&file_base);
            println!(
                "Generated `{}`.\nWire in `main.rs`:\n  mod routes;\n  .nest(\"{prefix}\", routes::{module}::router())",
                path.display(),
            );
        }
        _ => bail!("--style must be `macro` or `functional`"),
    }

    Ok(())
}

pub fn route(controller: &str, method: &str, path: &str, force: bool) -> Result<()> {
    let struct_name = controller_struct_name(controller);
    let file_base = struct_name_to_snake_file(&struct_name);
    let file_path = PathBuf::from("src/controllers").join(format!("{file_base}.rs"));

    if !file_path.exists() {
        bail!(
            "controller file not found: {} — run `oxide generate controller {}` first",
            file_path.display(),
            controller
        );
    }

    let http = method.trim().to_ascii_uppercase();
    validate_http_method(&http)?;
    validate_route_path(path)?;

    let attr = route_attr(&http)?;
    let fn_name = route_fn_name(&http, path);
    let duplicate_needle = format!("#[{attr}(\"{path}\")]");
    let existing = fs::read_to_string(&file_path)
        .with_context(|| format!("read {}", file_path.display()))?;
    if existing.contains(&duplicate_needle) && !force {
        bail!(
            "route already exists: {} {} — use `--force` to add anyway",
            http,
            path
        );
    }

    let block = format!(
        r#"
    #[{attr}("{path}")]
    async fn {fn_name}(&self) -> ::oxide_framework_core::ApiResponse<Msg> {{
        ::oxide_framework_core::ApiResponse::ok(Msg {{
            text: "generated by oxide".into(),
        }})
    }}

"#,
    );

    let updated = if let Some(idx) = existing.find(ROUTE_MARKER) {
        let before = &existing[..idx];
        let after_marker = &existing[idx..];
        format!("{before}{block}{after_marker}")
    } else {
        insert_before_impl_close(&existing, &struct_name, &block)?
    };

    fs::write(&file_path, updated).with_context(|| format!("write {}", file_path.display()))?;
    println!(
        "Added `{http} {path}` → `{fn_name}` in `{}`",
        file_path.display()
    );
    Ok(())
}

pub fn middleware(name: &str, force: bool) -> Result<()> {
    validate_snake_name(name)?;
    let dir = PathBuf::from("src/middleware");
    fs::create_dir_all(&dir).with_context(|| format!("create {}", dir.display()))?;
    let path = dir.join(format!("{name}.rs"));

    if path.exists() && !force {
        bail!("`{}` already exists — use `--force` to overwrite", path.display());
    }

    let contents = middleware_template(name);
    fs::write(&path, contents).with_context(|| format!("write {}", path.display()))?;

    let mod_rs = dir.join("mod.rs");
    if !mod_rs.exists() {
        fs::write(
            &mod_rs,
            format!("//! Application middleware.\n\nmod {name};\npub use {name}::*;\n"),
        )?;
    } else {
        let mut s = fs::read_to_string(&mod_rs)?;
        let line = format!("mod {name};");
        if !s.contains(&line) {
            s.push_str(&format!("\nmod {name};\npub use {name}::*;\n"));
            fs::write(&mod_rs, s)?;
        }
    }

    println!(
        "Created `{}`. Implement a `tower::Layer` and attach with `App::layer(...)`.",
        path.display()
    );
    Ok(())
}

fn write_macro_controller(path: &std::path::Path, struct_name: &str, prefix: &str, _force: bool) -> Result<()> {
    validate_prefix(prefix)?;
    let contents = format!(
        r#"//! Generated by `oxide generate controller`.

use oxide_framework_core::{{controller, ApiResponse}};
use serde::Serialize;

#[derive(Default)]
pub struct {struct_name};

#[derive(Serialize)]
struct Msg {{
    text: String,
}}

#[controller("{prefix}")]
impl {struct_name} {{
    #[get("/")]
    async fn index(&self) -> ApiResponse<Msg> {{
        ApiResponse::ok(Msg {{
            text: "Hello from {struct_name}".into(),
        }})
    }}

    {ROUTE_MARKER}
}}
"#
    );
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
    }
    fs::write(path, contents).with_context(|| format!("write {}", path.display()))?;
    Ok(())
}

fn write_functional_routes(path: &std::path::Path, name: &str, prefix: &str, _force: bool) -> Result<()> {
    validate_prefix(prefix)?;
    let fn_prefix = snake_module_name(&struct_name_to_snake_file(&controller_struct_name(name)));
    let contents = format!(
        r#"//! Functional `OxideRouter` module (generated by `oxide generate controller --style functional`).

use oxide_framework_core::{{ApiResponse, OxideRouter}};
use serde::Serialize;

#[derive(Serialize)]
struct Msg {{
    text: String,
}}

pub fn router() -> OxideRouter {{
    OxideRouter::new()
        .get("/", {fn_prefix}_index)
}}

async fn {fn_prefix}_index() -> ApiResponse<Msg> {{
    ApiResponse::ok(Msg {{
        text: "functional routes ({name})".into(),
    }})
}}
"#
    );
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
    }
    fs::write(path, contents).with_context(|| format!("write {}", path.display()))?;
    Ok(())
}

fn upsert_controllers_mod(struct_name: &str, file_base: &str) -> Result<()> {
    let mod_path = PathBuf::from("src/controllers/mod.rs");
    let mod_line = format!("mod {file_base};");
    let use_line = format!("pub use {file_base}::{struct_name};");

    if !mod_path.exists() {
        fs::write(
            &mod_path,
            format!("//! Controllers.\n\n{mod_line}\n{use_line}\n"),
        )?;
        return Ok(());
    }

    let mut s = fs::read_to_string(&mod_path)?;
    if !s.contains(&mod_line) {
        s.push_str(&format!("\n{mod_line}\n{use_line}\n"));
        fs::write(&mod_path, s)?;
    }
    Ok(())
}

fn upsert_routes_mod(file_base: &str) -> Result<()> {
    let mod_path = PathBuf::from("src/routes/mod.rs");
    let mod_line = format!("mod {file_base};");
    let pub_use = format!("pub use {file_base}::*;");

    if !mod_path.exists() {
        fs::write(
            &mod_path,
            format!("//! Functional route modules.\n\n{mod_line}\n{pub_use}\n"),
        )?;
        return Ok(());
    }

    let mut s = fs::read_to_string(&mod_path)?;
    if !s.contains(&mod_line) {
        s.push_str(&format!("\n{mod_line}\n{pub_use}\n"));
        fs::write(&mod_path, s)?;
    }
    Ok(())
}

fn insert_before_impl_close(src: &str, struct_name: &str, block: &str) -> Result<String> {
    let needle = format!("impl {struct_name}");
    let pos = src.find(&needle).with_context(|| {
        format!(
            "could not find `{needle}` — add `{ROUTE_MARKER}` before the closing `}}` of the impl block, or fix the struct name"
        )
    })?;
    let bytes = src.as_bytes();
    let mut i = pos + needle.len();
    while i < bytes.len() && bytes[i].is_ascii_whitespace() {
        i += 1;
    }
    if bytes.get(i) == Some(&b'{') {
        i += 1;
    } else {
        bail!("expected `{{` after `{needle}`");
    }
    let mut depth = 1u32;
    while i < bytes.len() {
        match bytes[i] {
            b'{' => depth += 1,
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    let insert_at = i;
                    let mut out = String::new();
                    out.push_str(&src[..insert_at]);
                    out.push_str(block);
                    out.push_str(&src[insert_at..]);
                    return Ok(out);
                }
            }
            _ => {}
        }
        i += 1;
    }
    bail!("unclosed `impl {struct_name}` block");
}

fn middleware_template(name: &str) -> String {
    format!(
        r#"//! Middleware stub: `{name}` — replace with a real `tower::Layer`.

use std::task::{{Context, Poll}};
use tower::{{Layer, Service}};

#[derive(Clone, Default)]
pub struct {pascal};

impl<S> Layer<S> for {pascal} {{
    type Service = {pascal}Service<S>;

    fn layer(&self, inner: S) -> Self::Service {{
        {pascal}Service {{ inner }}
    }}
}}

#[derive(Clone)]
pub struct {pascal}Service<S> {{
    inner: S,
}}

impl<S, Req> Service<Req> for {pascal}Service<S>
where
    S: Service<Req> + Send + Clone + 'static,
    S::Future: Send + 'static,
    Req: Send + 'static,
{{
    type Response = S::Response;
    type Error = S::Error;
    type Future = S::Future;

    fn poll_ready(&mut self, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {{
        self.inner.poll_ready(cx)
    }}

    fn call(&mut self, req: Req) -> Self::Future {{
        self.inner.call(req)
    }}
}}
"#,
        pascal = snake_to_pascal(name),
    )
}

fn snake_to_pascal(name: &str) -> String {
    name.split('_')
        .map(|w| {
            let mut it = w.chars();
            match it.next() {
                None => String::new(),
                Some(f) => {
                    let mut s = f.to_uppercase().to_string();
                    s.push_str(it.as_str());
                    s
                }
            }
        })
        .collect()
}

fn controller_struct_name(input: &str) -> String {
    let s = input.trim();
    if s.ends_with("Controller") {
        s.to_string()
    } else {
        format!("{}Controller", to_upper_camel(s))
    }
}

fn struct_name_to_snake_file(struct_name: &str) -> String {
    let base = struct_name.strip_suffix("Controller").unwrap_or(struct_name);
    format!("{}_controller", to_snake_case(base))
}

fn to_upper_camel(s: &str) -> String {
    s.split(|c: char| c == '_' || c == '-' || c == ' ')
        .filter(|p| !p.is_empty())
        .map(|w| {
            let mut it = w.chars();
            match it.next() {
                None => String::new(),
                Some(f) => std::iter::once(f.to_ascii_uppercase()).chain(it).collect(),
            }
        })
        .collect()
}

fn to_snake_case(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(c.to_ascii_lowercase());
    }
    if out.is_empty() {
        s.to_lowercase()
    } else {
        out
    }
}

fn snake_module_name(file_base: &str) -> String {
    file_base
        .strip_suffix("_controller")
        .unwrap_or(file_base)
        .replace('-', "_")
}

fn validate_prefix(prefix: &str) -> Result<()> {
    if !prefix.starts_with('/') {
        bail!("prefix must start with `/`, got `{prefix}`");
    }
    Ok(())
}

fn validate_route_path(path: &str) -> Result<()> {
    if !path.starts_with('/') {
        bail!("route path must start with `/`, got `{path}`");
    }
    Ok(())
}

fn validate_http_method(m: &str) -> Result<()> {
    match m {
        "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "HEAD" | "OPTIONS" => Ok(()),
        _ => bail!("unsupported HTTP method `{m}` — use GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS"),
    }
}

fn route_attr(http: &str) -> Result<&'static str> {
    Ok(match http {
        "GET" => "get",
        "POST" => "post",
        "PUT" => "put",
        "DELETE" => "delete",
        "PATCH" => "patch",
        "HEAD" => "head",
        "OPTIONS" => "options",
        _ => bail!("unsupported method"),
    })
}

fn route_fn_name(http: &str, path: &str) -> String {
    let base = path
        .trim_matches('/')
        .replace(['/', '{', '}'], "_")
        .replace('-', "_");
    let base = if base.is_empty() {
        "root".into()
    } else {
        base
    };
    let prefix = http.to_ascii_lowercase();
    format!("{prefix}_{base}")
}

fn validate_snake_name(name: &str) -> Result<()> {
    if name.is_empty()
        || !name
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
    {
        bail!("middleware name must be snake_case ASCII");
    }
    Ok(())
}

