//! `oxide new` — scaffold a new application crate.

use anyhow::{Context, Result, bail};
use std::fs;
use std::path::{Path, PathBuf};

pub fn run(name: &str, force: bool, oxide: &str) -> Result<()> {
    validate_name(name)?;
    let root = PathBuf::from(name);
    if root.exists() {
        if force {
            fs::remove_dir_all(&root).with_context(|| format!("remove {}", root.display()))?;
        } else {
            let is_empty = fs::read_dir(&root)
                .with_context(|| format!("read {}", root.display()))?
                .next()
                .is_none();
            if is_empty {
                fs::remove_dir(&root).with_context(|| format!("remove empty {}", root.display()))?;
            } else {
                bail!(
                    "destination `{}` already exists — use `--force` to overwrite (dangerous)",
                    root.display()
                );
            }
        }
    }

    let dep = parse_oxide_dep(oxide)?;

    fs::create_dir_all(root.join("src/controllers"))
        .with_context(|| format!("create {}", root.join("src/controllers").display()))?;

    write(
        &root.join("Cargo.toml"),
        &cargo_toml(name, &dep),
        force,
    )?;
    write(&root.join("app.yaml"), APP_YAML, force)?;
    write(&root.join(".gitignore"), GITIGNORE, force)?;
    write(&root.join("README.md"), &readme(name, oxide), force)?;
    write(&root.join("src/main.rs"), MAIN_RS, force)?;
    write(&root.join("src/controllers/mod.rs"), CONTROLLERS_MOD, force)?;
    write(
        &root.join("src/controllers/hello_controller.rs"),
        HELLO_CONTROLLER,
        force,
    )?;

    println!(
        "Created Oxide project `{}` — `cd {}` then `cargo run`",
        name,
        root.display()
    );
    Ok(())
}

fn validate_name(name: &str) -> Result<()> {
    if name.is_empty()
        || name.contains(['/', '\\'])
        || name == "."
        || name == ".."
    {
        bail!("invalid project name `{name}`");
    }
    if !name
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
    {
        bail!("project name should use letters, digits, `-`, or `_`");
    }
    Ok(())
}

fn parse_oxide_dep(oxide: &str) -> Result<String> {
    let oxide = oxide.trim();
    if let Some(p) = oxide.strip_prefix("path=") {
        let p = p.trim().trim_matches('"');
        if p.is_empty() {
            bail!("--oxide path=... needs a non-empty path");
        }
        return Ok(format!("oxide_framework_core = {{ path = \"{p}\" }}"));
    }
    if let Some(v) = oxide.strip_prefix("version=") {
        let v = v.trim().trim_matches('"');
        if v.is_empty() {
            bail!("--oxide version=... needs a version");
        }
        return Ok(format!("oxide_framework_core = \"{v}\""));
    }
    bail!("--oxide must be `path=../oxide_framework_core` or `version=0.1.0`");
}

fn cargo_toml(crate_name: &str, oxide_dep: &str) -> String {
    format!(
        r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2024"

# Standalone workspace so this crate works when created inside another repo (e.g. Oxide itself).
[workspace]

[dependencies]
{oxide_dep}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
tokio = {{ version = "1", features = ["full"] }}
"#
    )
}

fn write(path: &Path, contents: &str, _force: bool) -> Result<()> {
    fs::write(path, contents).with_context(|| format!("write {}", path.display()))
}

fn readme(name: &str, oxide: &str) -> String {
    format!(
        r#"# {name}

Generated by `oxide new`.

## Run

```bash
cargo run
```

## `oxide_framework_core` dependency

This template uses:

`--oxide {oxide}`

Adjust `Cargo.toml` if your layout differs (e.g. publish to crates.io and use a version).

## Next steps

- Edit `app.yaml` (host, port, `app_name`)
- Add controllers under `src/controllers/` (`oxide generate controller --help`)
"#
    )
}

const APP_YAML: &str = r#"host: "127.0.0.1"
port: 3000
app_name: "my-oxide-app"
"#;

const GITIGNORE: &str = r#"/target
Cargo.lock
"#;

const MAIN_RS: &str = r#"//! Oxide application entry point.

use oxide_framework_core::{ApiResponse, App, Config};
use serde::Serialize;

mod controllers;

#[derive(Serialize)]
struct Message {
    text: String,
}

async fn index(Config(cfg): Config) -> ApiResponse<Message> {
    ApiResponse::ok(Message {
        text: format!("Welcome to {}!", cfg.app_name),
    })
}

fn main() {
    App::new()
        .config("app.yaml")
        .get("/", index)
        .controller::<controllers::HelloController>()
        .run();
}
"#;

const CONTROLLERS_MOD: &str = r#"//! Generated controllers.

mod hello_controller;

pub use hello_controller::HelloController;
"#;

const HELLO_CONTROLLER: &str = r#"//! Example `#[controller]` — add routes with `oxide generate route`.

use oxide_framework_core::{controller, ApiResponse};
use serde::Serialize;

#[derive(Default)]
pub struct HelloController;

#[derive(Serialize)]
struct Msg {
    text: String,
}

#[controller("/api/hello")]
impl HelloController {
    #[get("/")]
    async fn index(&self) -> ApiResponse<Msg> {
        ApiResponse::ok(Msg {
            text: "Hello from HelloController".into(),
        })
    }

    // oxide-framework-cli:routes
}
"#;

